apiVersion: v2
name: crossplane
appVersion: 0.0.1
description: |
  Upbound Crossplane (UXP) is Upbound's official enterprise-grade
  distribution of Crossplane. It's fully compatible with upstream Crossplane,
  and providing additional features such as a local Web UI, and
  maintained by Upbound. It's the easiest way for both individual community
  members and enterprises to build their production control planes.
version: 0.0.1
icon: https://raw.githubusercontent.com/upbound/upbound-crossplane/66ce9eb2c5a0c3af8ed7d19551a2c4d743b933b9/docs/media/logo.png
home: https://upbound.io
maintainers:
  - name: Upbound Inc.
    email: info@upbound.io
keywords:
  - cloud
  - infrastructure
  - services
  - application
  - database
  - cache
  - bucket
  - infra
  - app
  - ops
  - oam
  - gcp
  - azure
  - aws
  - alibaba
  - cloudsql
  - rds
  - s3
  - azuredatabase
  - asparadb
  - gke
  - aks
  - eks
dependencies:
  - name: uxp-controller-manager
    version: 0.1.0-rc.0.209.gfe6962e
    repository: oci://xpkg.upbound.io/upbound
    alias: upbound
  - name: uxp-webui
    version: 1.0.0
    repository: oci://xpkg.upbound.io/upbound
    alias: webui
    condition: webui.enabled
  - name: uxp-apollo
    version: 0.0.0-110.g5127447
    repository: oci://xpkg.upbound.io/upbound
    alias: apollo
    condition: webui.enabled
